# Generated by Django 5.0.6 on 2024-06-29 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                (
                    "email",
                    models.EmailField(
                        max_length=150, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank="True", null="True", verbose_name="комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_letter",
                    models.CharField(max_length=250, verbose_name="тема письма"),
                ),
                ("body_letter", models.TextField(verbose_name="тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название рассылки"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="время старта рассылки",
                    ),
                ),
                (
                    "next_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="время следующей рассылки",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        default=None, verbose_name="время окончания рассылки"
                    ),
                ),
                ("period", models.IntegerField(verbose_name="периодичность")),
                ("status", models.BooleanField(verbose_name="статус рассылки")),
                (
                    "is_activated",
                    models.BooleanField(default=True, verbose_name="действующая"),
                ),
                (
                    "customer",
                    models.ManyToManyField(
                        to="mail_service.customer", verbose_name="кому"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank="True",
                        null="True",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mail_service.message",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="дата и время последней отправки попытки",
                    ),
                ),
                ("status", models.BooleanField(verbose_name="статус попытки")),
                (
                    "response_server",
                    models.CharField(
                        blank="True",
                        max_length=150,
                        null="True",
                        verbose_name="ответ почтового сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        blank="True",
                        null="True",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mail_service.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки по почте",
                "verbose_name_plural": "Попытки отправки по почте",
            },
        ),
    ]
