# Generated by Django 5.0.6 on 2024-05-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "verbose_name": "Попытка отправки по почте",
                "verbose_name_plural": "Попытки отправки по почте",
            },
        ),
    ]
