# Generated by Django 5.0.6 on 2024-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0002_alter_mailingattempt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="comment",
            field=models.TextField(
                blank="True", null="True", verbose_name="комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=150, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Ф.И.О."),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="date_time",
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name="дата и время последней отправки попытки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="response_server",
            field=models.CharField(
                blank="True",
                max_length=150,
                null="True",
                verbose_name="ответ почтового сервера",
            ),
        ),
    ]
