# Generated by Django 5.0.6 on 2024-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0002_customer_user_mailing_user_message_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="period",
            field=models.CharField(
                choices=[
                    ("once_a_day", "once_a_day"),
                    ("once_a_week", "once_a_week"),
                    ("once_a_month", "once_a_month"),
                ],
                default="once_a_day",
                max_length=12,
                verbose_name="периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("start", "start"),
                    ("finish", "finish"),
                    ("created", "created"),
                ],
                default="start",
                max_length=7,
                verbose_name="статус рассылки",
            ),
        ),
    ]
