# Generated by Django 5.0.6 on 2024-06-28 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0003_alter_customer_comment_alter_customer_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="date_time",
        ),
        migrations.AddField(
            model_name="mailing",
            name="customer",
            field=models.ManyToManyField(
                to="mail_service.customer", verbose_name="кому"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="end_date",
            field=models.DateTimeField(
                default=None, verbose_name="время окончания рассылки"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_activated",
            field=models.BooleanField(default=True, verbose_name="действующая"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.CASCADE,
                to="mail_service.message",
                verbose_name="сообщение",
            ),
            preserve_default="True",
        ),
        migrations.AddField(
            model_name="mailing",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=50,
                verbose_name="название рассылки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailing",
            name="next_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="время следующей рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="время старта рассылки"
            ),
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.CASCADE,
                to="mail_service.mailing",
                verbose_name="рассылка",
            ),
            preserve_default="True",
        ),
    ]
